server:
    port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/uniclub09
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

jwt:
  private-key: W5Qi1VGhjbOVWdDuo2IJGJQiI1FuRsvV1m6X2Lhals4=
file:
  root-path: C:\CyberSoft\uniclub09\files\images